spring.application.name=IS_lab1

spring.datasource.url=jdbc:postgresql://localhost:2222/postgres
spring.datasource.username=postgres
spring.datasource.password=hkmp5sd6

spring.jpa.database-platform=org.eclipse.persistence.jpa.PersistenceProvider

spring.jpa.properties.eclipselink.weaving=static
spring.jpa.properties.eclipselink.ddl-generation=create-or-extend-tables
spring.jpa.properties.eclipselink.ddl-generation.output-mode=database
spring.jpa.properties.eclipselink.logging.level=FINE
spring.jpa.properties.eclipselink.logging.parameters=true

jwt.secretKey=3749871305701907513513571306501755475877686556769875457997564539678585884
jwt.expirationTime=900000000000000000