project.name=Lab3Web
project.version=1.0
main.class=Main

src.dir=src/main/java
lib.dir=lib
build.dir=build
classes.dir=${build.dir}/classes
jar.dir=${build.dir}/jar

alt.build.dir=buildAlt
alt.classes.dir=${alt.build.dir}/classes
alt.jar.dir=${alt.build.dir}/jar
alt.src.dir=${alt.build.dir}/src

test.src.dir=src/test/java
test.classes.dir=${build.dir}/test-classes
test.results.dir=${build.dir}/test-results

music.file=vy-pozvonili-tsariu-batiushke.mp3

native2ascii.dir=${build.dir}/native2ascii

svn.message=report-commit
test.report.dir=reports

alt.java.home=C:/Program Files/Java/jdk-17
alt.jvm.args=-Xmx512m -Dfile.encoding=UTF-8

critical.classes=(?s).*([^a-zA-Z0-9]|^)(ClockBean|Main)\\.java([^a-zA-Z0-9]|$).*
git.commit.message=auto-commit



team.dir=${build.dir}/team
team.zip=${build.dir}/revisions.zip

scp.host=s467846@se.ifmo.ru
scp.dir=:~
scp.port=2222
scp.user=s467846
scp.password=FIOF.4748

alt.match1=updateTime
alt.replace1=uT
alt.match2=checkHit
alt.replace2=cH

history.diff.file=history_diff.txt